FROM ubuntu:20.04
RUN apt-get update && apt-get install -y python3 python3-pip nano fish git curl rclone fuse
#
# to build shutdown image add rexec install
#
#RUN pip3 install git+https://github.com/datahub-projects/rexec#egg=rexec>=0.1.70
RUN pip3 install gputil ipython

WORKDIR /home/rexec/work

CMD ["/bin/bash"]
