compute:
  default: ec2_gpu

  services:
    ec2_gpu:
      provider: EC2
      default_image: "Deep Learning AMI (Ubuntu 18.04) Version 36.0"
      default_vmtype: g4dn.xlarge
      disksize: 250
      region: us-west-2
      gpu_enabled: true
      auth:
        access_key_id: AWSIDKEY
        secret_access_key: AWSSECRETKEY

    ec2_cpu:
      provider: EC2
      default_image: "ami-ubuntu-18.04-1.16.0-00-1569343567"
      default_vmtype: c5a.4xlarge
      disksize: 150
      region: us-west-2
      gpu_enabled: false
      auth:
        access_key_id: AWS_ID_KEY
        secret_access_key: AWS_SECRET_KEY

    gce_gpu:
      provider: GCE
      access: something.iam.gserviceaccount.com
      default_image: https://www.googleapis.com/compute/beta/projects/project_name/global/images/image
      default_size: n1-standard-4
      disksize: 250
      region: us-west1-b
      gpu_enabled: true
      #if enabled:
      ex_accelerator_type: nvidia-tesla-t4
      ex_accelerator_count: 1
      auth:
        project: projname
        type: service_account
        auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
        auth_uri: https://accounts.google.com/o/oauth2/auth
        client_email: user@project_name.iam.gserviceaccount.com
        client_id: '1234567890'
        client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/xxyyzz.iam.gserviceaccount.com
        token_uri: https://oauth2.googleapis.com/token
        private_key_id: GCP_ACCESS_KEY
        private_key: 
          '
          -----BEGIN PRIVATE KEY-----
            REDACTED
          -----END PRIVATE KEY-----
          '

storage:
  default: s3

  services:
    s3:
      provider: AWS
      region: us-west-2
      type: s3
      auth:
        access_key_id: AWS_ACCESS_KEY
        secret_access_key: AWS_SECRET_KEY
        acl: private
        env_auth: false
